version: '3.7'

services:
  web:
    build:
      context: ../
      dockerfile: ./container/Dockerfile
    command: gunicorn smi.wsgi:application --bind 0.0.0.0:8000 --max-requests 50 --timeout 180
    volumes:
      - static_volume:/home/app/web/static
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis

  celery:
    build:
      context: ../
      dockerfile: ./container/Dockerfile
    command: celery -A smi worker -l info
    env_file:
      - ./.env.prod
    depends_on:
      - web
      - db
      - redis

  celery-beat:
    build:
      context: ../
      dockerfile: ./container/Dockerfile
    command: celery -A smi beat -l info
    env_file:
      - ./.env.prod
    depends_on:
      - web
      - db
      - redis

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  redis:
    image: redis:alpine

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
      - ./.cert/:/etc/cert/site/
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: