# Generated by Django 3.1.7 on 2021-03-09 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0003_auto_20210309_1839'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Direction',
        ),
        migrations.DeleteModel(
            name='Indicator',
        ),
    ]
