# Generated by Django 3.1.7 on 2021-03-08 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant_id', models.PositiveIntegerField(unique=True, verbose_name='завод номер')),
                ('plantname', models.CharField(blank=True, max_length=128, null=True, verbose_name='Наименование завода')),
                ('firmtext', models.CharField(blank=True, max_length=128, null=True)),
                ('factory_link', models.CharField(blank=True, max_length=500, null=True)),
                ('tex_link', models.CharField(blank=True, max_length=500, null=True)),
                ('create_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factory_created', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factory_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('plantname',),
            },
        ),
    ]
