# Generated by Django 3.1.7 on 2021-03-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Created', 'Заказ создан в SMI'), ('Send', 'Заказ отправлен в SAP'), ('Success', 'Заказ успешно был создан SAP'), ('Error', 'Заказ не создан SAP (Ошибка)'), ('EditError', 'EditError'), ('EditMesError', 'EditMesError'), ('MesSend', 'Заказ отправлен в MES'), ('MesSuccess', 'Заказ успешно был создан MES'), ('MesError', 'Заказ не создан MES (Ошибка)'), ('SmiError', 'SmiError'), ('SapError', 'SapError')], default='Created', max_length=50),
        ),
    ]
