# Generated by Django 3.1.7 on 2021-03-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210310_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='counter',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=13),
        ),
    ]
